// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBKYkjVura_JJxhr8gH-Sb4VX5wj7omQ8',
    appId: '1:568841915665:web:6cff610af5a9065bc510b0',
    messagingSenderId: '568841915665',
    projectId: 'chat-mini-curso',
    authDomain: 'chat-mini-curso.firebaseapp.com',
    storageBucket: 'chat-mini-curso.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWnB_F9SjLUqxoz4o6dvuIbtQgfMmgnSY',
    appId: '1:568841915665:android:4dfbbc016c838c47c510b0',
    messagingSenderId: '568841915665',
    projectId: 'chat-mini-curso',
    storageBucket: 'chat-mini-curso.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAyR1yB3ATMMz5o3z1YBhxALixDeZ9pks',
    appId: '1:568841915665:ios:12d85d14d549595dc510b0',
    messagingSenderId: '568841915665',
    projectId: 'chat-mini-curso',
    storageBucket: 'chat-mini-curso.firebasestorage.app',
    iosBundleId: 'com.example.chatAppMiniCurso',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAyR1yB3ATMMz5o3z1YBhxALixDeZ9pks',
    appId: '1:568841915665:ios:12d85d14d549595dc510b0',
    messagingSenderId: '568841915665',
    projectId: 'chat-mini-curso',
    storageBucket: 'chat-mini-curso.firebasestorage.app',
    iosBundleId: 'com.example.chatAppMiniCurso',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBKYkjVura_JJxhr8gH-Sb4VX5wj7omQ8',
    appId: '1:568841915665:web:46965d2cc2666164c510b0',
    messagingSenderId: '568841915665',
    projectId: 'chat-mini-curso',
    authDomain: 'chat-mini-curso.firebaseapp.com',
    storageBucket: 'chat-mini-curso.firebasestorage.app',
  );
}
